### ISSUE TITLE
Parflow versus WRF-Hydro

### ISSUE THREAD

**Issue by cathieO** [hydroframe/Subsetting#2]
Produce a write-up that is intended for an incoming graduate student.
For each of Parflow, WRF-Hydro (national water model is a configuration of WRF-Hydro)
 - who originated the model?
 - what is it used for?
   - Is this an operational model?
   - Is this a research model?
  (what do those two terms mean and why is the distinction important?)
From the CS side the two probably look similar. Operational models are more "battle tested" 
 - what are the "core equation" being solved for each?

Practical considerations:
 - where does on find them?
 - How are they installed?
 - How do you run each of them?

**Comment by arezaii** [comment]
I am confused about the terminology here: "For each of Parflow, WRF-Hydro..." 
My understanding is that these are both software tools, but the task makes them each sound like they're "models" unto themselves. Logically, I am assuming this task is to identify the difference between the NWM (created using WRF-Hydro) and CONUS 1.0 (created using Parflow), but I am not certain. 

@cathieO @LejoFlores  could I get your input/clarifying remarks?

**Comment by LejoFlores** [comment]
In this context the "model" is either WRF-Hydro or ParFlow, but there is a whole tool stack that is still required to do preprocessing, potentially manage runs in an HPC environment (i.e., Matt's scripts), and or post-processing that needs to be done. 

I guess the convention, although there's no rigorous definition, is that an operational model is more "battle hardened" against potential faults and has a more clearly identified update/refresh cycle and fewer active developers.
