### ISSUE TITLE
Retrieve data for WRF-Hydro

### ISSUE THREAD

**Issue by cathieO** [hydroframe/Subsetting#4]
this data will come from?
Danielle (CHUASI) put together a national water model subsetter - gets the dataset for given basins. HUC-8 and we need HUC-4 (which is more course) of the Snake River Basin

https://en.wikipedia.org/wiki/Hydrological_code
HUC-17 is the Pacific northwest
HUC-1702 is the next finer scale

**Comment by arezaii** [comment]
From the repo https://github.com/CUAHSI/nwm_subsetting/tree/develop, the data restriction is HUC-12, not HUC-8, although the documents state that this limit isn't enforced. I'm wondering if we can get the HUC-4 data just by asking the web service for it? http://subset.cuahsi.org/

**Comment by arezaii** [comment]
@LejoFlores are you wanting all of HUC-1705 and HUC-1704?

**Comment by LejoFlores** [comment]
yes, and 1706... apparently, these are referred to as "subregions" in USGS lexicon: https://water.usgs.gov/GIS/huc_name.html#Region17

**Comment by arezaii** [comment]
I abused the API to generate this subset, it will include HUCs that were not requested, but fall within the bounding box created by the requested HUCs.

http://subset.cuahsi.org/status/7a3773dc616d1f404683f1f5cc586a82dd28d139

@LejoFlores I need some help making sure that the data is correct and valid. 

Initial review suggests that data is correct and valid.
