### ISSUE TITLE
Subsetting from HUC8 to HUC4 (tools)

### ISSUE THREAD

**Issue by cathieO** [hydroframe/Subsetting#5]
Danielle has the ability to subset into a HUC8, but we need HUC4 which means that we need to change her tool to extract HUC4 rather than HUC8.

Where does her code live? http://subset.cuahsi.org/
https://github.com/CUAHSI/nwm_subsetting

**Comment by arezaii** [comment]
An overview of what I did to get a custom subset of HUC-4's:

![image](https://user-images.githubusercontent.com/2806014/60370352-a81a4380-99b3-11e9-96a5-9d7a2b418c1d.png)

**Comment by arezaii** [comment]
have to go back and redo this. Reliance on external web service is not desirable.
