### ISSUE TITLE
Subset from CONUS 1.0 using 

### ISSUE THREAD

**Issue by cathieO** [hydroframe/Subsetting#7]
@hoangtv1899 has developed a subsetting tool that we will need to use to get the same geographic subset as #5 which was for WRF-Hydro.

**Comment by arezaii** [comment]
I believe we can use a shapefile generated from https://viewer.nationalmap.gov/basic/ which can give us the subregions of interest (1704, 1705, 1706) and then use a GIS tool like QGIS to combine them into a single shapefile for subsetting CONUS using the clip_inputs and create_subdomain tools in this repo.

**Comment by hoangtv1899** [comment]
Hi Arezaii,

I think that's not a right way to do subsetting using shapefile. Tony and Danielle just discussed with me last week and I think they found a way to combine multi subregions of interest from HUC4 or HUC8 for subsetting. If can, you and Cathie can coordinate with them please? We are working on developing and fixing the codes but new update might not coming after next meeting with Tony and Danielle.

Thanks,
Hoang

**Comment by arezaii** [comment]
For clarification: @hoangtv1899 are you saying we should not be using shapefiles at all to subset? OR just that my idea of combining multiple shapes into one is not the correct way to produce the shapefile for input?

**Comment by hoangtv1899** [comment]
Hi @arezaii I mean that the other group from CUAHSI has already did combining multiple shapes into one for subsetting (http://subset.cuahsi.org/parflow/v1_0). Maybe you can email them (Danielle dtijerina@cuahsi.org) to avoid duplication?
Thanks!

**Comment by LejoFlores** [comment]
hey @hoangtv1899, I didn't know this was a thing! This is awesome and will be an exceptional help... thanks for showing us! @arezaii had made some scripts to get bigger cutouts for from the NWM/WRF-Hydro from Danielle's other app, so we should be able to do the same.

**Comment by hoangtv1899** [comment]
Thank you @LejoFlores for your encouragement. I'm so glad to hear about progress from other team members too!
Also, @reedmaxwell  and @lecondon have an idea about a bi-weekly meeting between people who either develop new codes or use the codes from this project to meet and talk (a longer version of SCRUM that @cathieO suggested). I think this also a great chance to better coordinate and avoid potential duplication. I just give a head up and maybe @lecondon will follow up with a more detail email later.
Thank you again team!
